# Generated by Django 2.1.7 on 2019-03-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='True if the user has access to the admin page.', verbose_name='Has Admin Access?'),
        ),
    ]
